name: Template CryptoCapBot Python application

on:
  push:
    branches: ["main"] # TODO: rename

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute python script
        env: # Or as an environment variable
          DEBUG: 0
          LIVE: 0
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_KEY_SECRET: ${{ secrets.TW_CONSUMER_KEY_SECRET }}
          MG_USER: ${{ secrets.MG_USER }}
          MG_PASSWORD: ${{ secrets.MG_PASSWORD }}
          MG_CLUSTER: ${{ secrets.MG_CLUSTER }}
          # TODO: add more
        run: |
          python twitter_bots/bot.py
